baseURL = "http://localhost:1313/"
title = "ramonvermeulen.dev"
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 30
paginate = 10
disableKinds = ["taxonomy", "term"]
theme = "hugo-telegraph"
themesDir = "themes"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[security]
  [security.node]
    [security.node.permissions]
      disable = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'

[module]
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[params]
  description = "Software & Cloud Engineer with a strong background in Google Cloud Platform."
  themeColor = "#111111"
  backgroundImage = "/img/background.png"
  siteName = "ramonvermeulen"
  siteDomainExtension = ".dev"
  sourceCodeLabel = "GitHub"
  sourceCodeURL = "https://github.com/ramonvermeulen/ramonvermeulen.dev"

[menu]
[[menu.main]]
  name = "About"
  pageRef = "/"
  weight = 10
[[menu.main]]
  name = "Experience"
  pageRef = "/experience"
  weight = 20
[[menu.main]]
  name = "Blog"
  pageRef = "/blog"
  weight = 30
